---
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy

lint:
  name: yamllint

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

platforms:
  - name: ${name:-instance}
    image: ${image:-centos:7}
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    # privileged: true
    groups:
      - ${pygroup:-python}
    environment:
      container: docker

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        ansible_user: ansible
      python3:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: testinfra
  options:
    v: 1
  lint:
    name: flake8
